create table if not exists inbox (
    event_id varchar(36) primary key,
    processed_at timestamp default current_timestamp not null
);
create table if not exists outbox (
    id bigint generated by default as identity primary key,
    topic varchar(100) not null,
    message_key varchar(36) not null,
    payload varchar(10000) not null,
    created_at timestamp default current_timestamp not null
);
